services:
  mongodb:
    image: mongo
    container_name: exam-creator-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: freecodecamp
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - exam-creator-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  exam-creator-network:
    driver: bridge
